using System;
using System.Collections.Generic;

namespace PowerAPI.Data.Models
{
    public partial class InsuranceNoteGeneratedQuotation
    {
        public string CompanyId { get; set; }
        public string DivisionId { get; set; }
        public string DepartmentId { get; set; }
        public string InvoiceNumber { get; set; }
        public string NoteTypeId { get; set; }
        public string PolicyBrokerId { get; set; }
        public string ActualPolicyBrokerId { get; set; }
        public string PolicyUnderwriterId { get; set; }
        public string PackagePololicyId { get; set; }
        public string EndorsementId { get; set; }
        public string CustomerId { get; set; }
        public string VendorId { get; set; }
        public string BusinessClassId { get; set; }
        public string RiskTypeId { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? Renewaldate { get; set; }
        public string PremiumDescription { get; set; }
        public decimal? SumInsured { get; set; }
        public decimal? BasicRate { get; set; }
        public string PremiumFomular { get; set; }
        public decimal? PremiumDue { get; set; }
        public decimal? InsuranceRate1 { get; set; }
        public decimal? InsuranceRate2 { get; set; }
        public decimal? InsuranceRate3 { get; set; }
        public decimal? Discount1 { get; set; }
        public decimal? Discount2 { get; set; }
        public decimal? Discount3 { get; set; }
        public decimal? BuyBack1 { get; set; }
        public decimal? BuyBack2 { get; set; }
        public decimal? BuyBack3 { get; set; }
        public decimal? BrokerCommissionRate { get; set; }
        public decimal? BrokerCommisson { get; set; }
        public decimal? Vatrate { get; set; }
        public decimal? Vatdue { get; set; }
        public decimal? NetDue { get; set; }
        public string PremiumTypeId { get; set; }
        public string ContractTypeId { get; set; }
        public string IncomeTypeId { get; set; }
        public string NoteStatus { get; set; }
        public string GenerateBy { get; set; }
        public string ApprovedBy { get; set; }
        public string ProjectTypeId { get; set; }
        public string ProjectId { get; set; }
        public string GldebtorsAccount { get; set; }
        public string GlcommissionAccount { get; set; }
        public string Glvataccount { get; set; }
        public string Glcogaccount { get; set; }
        public string CurrencyId { get; set; }
        public decimal? CurrencyExchangeRate { get; set; }
        public string TaxGroupId { get; set; }
        public bool? Cleared { get; set; }
        public string ClearedBy { get; set; }
        public DateTime? ClearedDate { get; set; }
        public bool? Void { get; set; }
        public string VoidBy { get; set; }
        public DateTime? VoidDate { get; set; }
        public bool? Posted { get; set; }
        public string PostedBy { get; set; }
        public DateTime? PostedDate { get; set; }
        public bool? FlatAmount { get; set; }
        public DateTime? EnteredDate { get; set; }
        public string LockedBy { get; set; }
        public DateTime? LockTs { get; set; }
        public DateTime? CoverStart { get; set; }
        public string NoteFormularDesc { get; set; }
        public double? NoOfEmployee { get; set; }
        public decimal? Basic { get; set; }
        public decimal? BurglaryExtension { get; set; }
        public decimal? CashInPersonalCustody { get; set; }
        public decimal? CashInSafePremises { get; set; }
        public decimal? CashInTransit { get; set; }
        public decimal? ElectricalMechanicalBdloading { get; set; }
        public decimal? ExcessBuyBack { get; set; }
        public decimal? Flood { get; set; }
        public decimal? FlueGas { get; set; }
        public decimal? Iarloading { get; set; }
        public decimal? LocalMedicalExpenses { get; set; }
        public decimal? MultiplierI { get; set; }
        public decimal? MultiplierIi { get; set; }
        public decimal? NonOccupationalRisksLoading { get; set; }
        public decimal? RothersI { get; set; }
        public decimal? RothersIi { get; set; }
        public decimal? RothersIii { get; set; }
        public decimal? OverseasMedicalExpenses { get; set; }
        public decimal? Perils { get; set; }
        public decimal? Srccommotion { get; set; }
        public decimal? Tarrif { get; set; }
        public decimal? ThirdPartyPd { get; set; }
        public decimal? Deductible { get; set; }
        public decimal? Fea { get; set; }
        public decimal? Fleet { get; set; }
        public decimal? GroupD { get; set; }
        public decimal? Lta { get; set; }
        public decimal? Ncd { get; set; }
        public decimal? DothersI { get; set; }
        public decimal? DothersIi { get; set; }
        public decimal? DothersIii { get; set; }
        public decimal? DothersIv { get; set; }
        public decimal? PackageD { get; set; }
        public decimal? SilentRisk { get; set; }
        public decimal? SpecialD { get; set; }
        public decimal? StockDeclarationD { get; set; }
        public string CustomerName { get; set; }
        public string EmployeeId { get; set; }
        public string ReceiptId { get; set; }
        public double? ReceiptAmount { get; set; }
        public string BankId { get; set; }
        public DateTime? PaymentDueDate { get; set; }
        public DateTime? InvoiceDueDate { get; set; }
        public double? DiscountPercentage { get; set; }
        public double? DiscountedPpd { get; set; }
        public string DebitNoteFullId { get; set; }
        public decimal? PremiumWithoutDiscount { get; set; }
        public decimal? PremiumAfterDiscount { get; set; }
        public decimal? PremiumAfterAllDeductions { get; set; }
        public decimal? PremiumAfterDiscountPlusPpd { get; set; }
        public decimal? DiscountValue { get; set; }
        public decimal? Ppdvalue { get; set; }
        public decimal? OtherDeductions { get; set; }
        public bool? Quotation { get; set; }
        public DateTime? PostingDate { get; set; }
        public string InsuranceCategoryId { get; set; }
        public bool? QuotationCleared { get; set; }
        public DateTime? QuotationClearedDate { get; set; }
        public string QuotationClearedBy { get; set; }
        public string ReportHeaderDescription { get; set; }
        public bool? Merged { get; set; }
        public string Session { get; set; }
        public string QuotationPrintedBy { get; set; }
        public DateTime? QuotationPrintedDate { get; set; }
        public bool? QuotationPrinted { get; set; }
        public int? QuotationExpiryDate { get; set; }
        public double? AppliedAmount { get; set; }
        public double? BalanceDue { get; set; }
        public bool? QuotationUsed { get; set; }
        public bool? ReCreated { get; set; }
        public bool? QuotationClosed { get; set; }
        public bool? Memorize { get; set; }
        public string BranchCode { get; set; }
    }
}
